### ISSUE TITLE
Version 0.6.4 - unable to view status of multiple boxes or set box as the default for a project

### ISSUE THREAD

**Issue by ssnyder** [junichi11/netbeans-vagrant-plugin#44]
I just installed NetBeans, and am trying to get the Vagrant plugin to work with my various boxes.  I can run the global-status command, but it's kind of a pain not being able to associate my Vagrant box with my project so it's easier to bring it up/down, exec a command, etc.

Thanks!

**Comment by junichi11** [comment]
@ssnyder I'm not sure what you expect yet. Could you write your actual and expected results? (with screenshots, version of vagrant, e.t.c if possible)

Thanks.

**Comment by ssnyder** [comment]
Sorry - I wasn't more specific. I just updated to vagrant 1.7.3 (behavior is unchanged).  I have multiple vagrant boxes (they are recognized by the vagrant options (see picture)
![screenshot 5](https://cloud.githubusercontent.com/assets/1420892/8750892/fe6d00f4-2c77-11e5-8e03-688318a4a9ae.jpg)

My project properties are:
![screenshot 6](https://cloud.githubusercontent.com/assets/1420892/8750923/2e749118-2c78-11e5-85af-d5229b6f14e2.jpg)

I don't see how I can associate a vagrant box with my project - so that is the box I resume, run commands on, etc. by default.  

I thought I read that this is now available on this version of the plugin?  If not, I apologize....and would be willing to try and help test this out if you can develop it!

Thanks!

**Comment by ssnyder** [comment]
Oh and before I forget the status bar shows Vagrant not created.  So clearly there is a hidden setting somewhere that I don't have access to.

Thanks!

**Comment by junichi11** [comment]
@ssnyder 
I guess that you want to run some commands from your context menu but the plugin doesn't recognize your project as vagrant project. Is it so?

Perhaps, your project has a vagrant file but it doesn't exist below the project root. Is this right?
If so, you have to set your vagrant file path to project properties. But unfortunately, ruby module is not supported now. Maybe, we can't add a customizer for the vagrant plugin like the C/C++ module (#40).
But I think there is a workaround like it. 

Could you wait a while since I try to check that later? (I'm developing another module now. So, I can't do it soon, sorry)

Thanks.

**Comment by ssnyder** [comment]
Yes, you are correct, my vagrantfile is not below the project root.  Just let me know when you have something for me to try....I can be patient!

**Comment by junichi11** [comment]
I've added project type for ruby.
Could you try to test it ?
https://github.com/junichi11/netbeans-vagrant-plugin/releases/tag/v0.6.4 (0.6.4.2-dev)

![nb-vagrant-issue44-ruby](https://cloud.githubusercontent.com/assets/738383/8923870/ab657784-3531-11e5-9da0-efa93892b05f.png)

Thanks.

**Comment by ssnyder** [comment]
I installed it and no change, I don't see the project options you show above...here are my screenshots
![screenshot 7](https://cloud.githubusercontent.com/assets/1420892/9045140/34f58d2e-39ef-11e5-9b75-28f186f72f47.jpg)

Yes, I did install the new plugin....

![screenshot 8](https://cloud.githubusercontent.com/assets/1420892/9045143/38b895fa-39ef-11e5-8fde-0bc3a76846bc.jpg)

**Comment by junichi11** [comment]
@ssnyder 
Sorry, missing Rails project.
I've fix it : https://github.com/junichi11/netbeans-vagrant-plugin/releases/tag/v0.6.4 (0.6.4.3-dev)

Thanks.
