### ISSUE TITLE
Plugin doesn't find vagrant boxes of the projects

### ISSUE THREAD

**Issue by alexz707** [junichi11/netbeans-vagrant-plugin#45]
I updated virtualbox to 5.0 as well as vagrant to 1.7.4
Your plugin is at version: 0.6.4
OSX

In every project in netbeans the vagrantfile exists but the plugin doesn't show the boxes in the status field. When I right click on a project node and select vagrant up the following error appears:

/usr/bin/vagrant up
The provider 'virtualbox' that was requested to back the machine
'default' is reporting that it isn't usable on this system. The
reason is shown below:

Vagrant could not detect VirtualBox! Make sure VirtualBox is properly installed.
Vagrant uses the `VBoxManage` binary that ships with VirtualBox, and requires
this to be available on the PATH. If VirtualBox is installed, please find the
`VBoxManage` binary and add it to the PATH environmental variable.
Done.

When I enter the command via cmd line it works without a problem so it seems to be a plugin problem !?

Regards
Alex

**Comment by junichi11** [comment]
I'll try to check that. 

Thanks!

**Comment by junichi11** [comment]
@alexz707 
I updated virtualbox and vagrant to 5.0 and 1.7.4.
But I can't reproduce that.
![nb-vagrant-issue45](https://cloud.githubusercontent.com/assets/738383/8792727/10bd4530-2fa6-11e5-8817-594a0f98627b.png)


#### my environments:
Product Version: NetBeans IDE 8.0.2 (Build 201408251540)
Java: 1.7.0_80; Java HotSpot(TM) Client VM 24.80-b11
Runtime: Java(TM) SE Runtime Environment 1.7.0_80-b15
System: Linux version 3.2.0-87-generic-pae running on i386; UTF-8; 

#### NetBeans vagrant plugin version
0.6.4

**Comment by alexz707** [comment]
Thanks for looking into it.
I still can reproduce my problem :/
Right after the update (without a restart of the system) everything worked. After the restart all vagrant machines disappeared in the left window (where your aaaa machine is). Right clicking and selecting vagrant up just gives me the attached error.
On the cmd line in the project folder vagrant up starts the machine as before the update...

My environment:
Product Version: NetBeans IDE 8.0.2 (Build 201411181905)
Updates: NetBeans IDE is updated to version NetBeans 8.0.2 Patch 2
Java: 1.8.0_45; Java HotSpot(TM) 64-Bit Server VM 25.45-b02
Runtime: Java(TM) SE Runtime Environment 1.8.0_45-b14
System: Mac OS X version 10.10.4 running on x86_64; UTF-8; de_DE (nb)
Netbeans vagrant plugin: 0.6.4
Vagrant share plugin 1.1.4

![bildschirmfoto 2015-07-21 um 11 03 51](https://cloud.githubusercontent.com/assets/562324/8796982/0724c19a-2f99-11e5-9444-fba36ef650c4.png)

**Comment by junichi11** [comment]
> If VirtualBox is installed, please find the VBoxManage binary and add it to the PATH environmental variable.

Did you try to do it?

**Comment by alexz707** [comment]
Thanks for your reply...

After some research I found out that the symlink /usr/bin/VBoxManage is not installed by vbox anymore.
On OSX just add it again and everythink works again ;)

Maybe you want to add that to a FAQ / WIKI for others:

ln -s /Applications/VirtualBox.app/Contents/MacOS/VBoxManage /usr/bin/VBoxManage

Sorry for opening a bug, it's vboxes fault ;)
Regards
Alex

**Comment by junichi11** [comment]
I'll add this issue number to https://github.com/junichi11/netbeans-vagrant-plugin#troubleshooting :)

Thanks for telling me your workaround!

**Comment by junichi11** [comment]
I've added this to README.md [1].

[1] https://github.com/junichi11/netbeans-vagrant-plugin/blob/dev/README.md#vagrant-could-not-detect-virtualbox

Thanks.

**Comment by jwhulette** [comment]
I'm having the same issue. My VBoxManage binary is located in /usr/local/bin and my vagrant binary is located there also but vagrant cannot find it. Running /usr/local/bin/vagrant up from the command line in Netbeans works fine.
