### ISSUE TITLE
SSH into multiple distinct VM's causes authentication issues

### ISSUE THREAD

**Issue by alex-barylski** [junichi11/netbeans-vagrant-plugin#48]
First off, thank you for your efforts, this plugin has been awesome :)

One issue however, is that NetBeans or the plugin when SSH'ing into multiple VM's in the same NB instance causes the IDE to lose reference to the private key? The key exists BUT the plugin just can't seem to find it? I can usually log into one VM but when I spin up another login, and switch back to the previous VM this issue pops up.

I get this screen when trying to SSH:

![nbauth1](https://user-images.githubusercontent.com/4084940/28671750-62a7ee94-72a3-11e7-8f3a-534231b40235.PNG)

The work around (for me) is to find the following file:

`C:\Users\YOU\AppData\Roaming\NetBeans\8.X\config\Preferences\org\netbeans\modules\dlight\nativeexecution.properties
`

Which contains something like:

```
org.netbeans.modules.nativeexecution.api.util.Authentication_vagrant@127.0.0.1\:2222=C:\\Users\\ME.DOMAIN\Desktop\\Projects\\COMPANY\\PROJECT\\.vagrant\\machines\\default\\virtualbox\\private_key
org.netbeans.modules.nativeexecution.api.util.Authentication_vagrant@127.0.0.1\:2222.methods=gssapi-with-mic#1,publickey#1,keyboard-interactive#1,password#1
org.netbeans.modules.nativeexecution.api.util.Authentication_vagrant@127.0.0.1\:2222.timeout=10
org.netbeans.modules.nativeexecution.api.util.ConnectionManager_connection.history_0=vagrant@127.0.0.1:2222
vagrant@127.0.0.1\:2222_allGroups=1000
vagrant@127.0.0.1\:2222_groupId=1000
vagrant@127.0.0.1\:2222_userId=1000
```
If I clear this file and save - close NetBeans and re-open I then get this screen which allows me to select the private key:

![nbauth2](https://user-images.githubusercontent.com/4084940/28671918-dc7345d4-72a3-11e7-8194-db892376077c.PNG)

Am I doing something wrong? I am using Windows 10 - but I had the same issue with Ubuntu. 

Any ideas?

**Comment by junichi11** [comment]
Sorry, I'm not sure about that at the moment. Although I cannot promise anything, I try to look at it later... 

If there is a problem, please try to use "remote terminal" manually.
![nb-vagrant-issue48](https://user-images.githubusercontent.com/738383/29345640-062f1678-827b-11e7-9f64-0f6bea7aad2a.png)
