### ISSUE TITLE
Unable to save Vagrant script path

### ISSUE THREAD

**Issue by voytass** [junichi11/netbeans-vagrant-plugin#49]
Windows 7 x64, NetBeans 8.2 x64 + vagrant plugin 1.1.0, Vagrant 1.9.7
In plugin options I can't save path to the vagrant.exe file. Path is always cleared up.
Workaround: edit manually a config file (_AppData\Roaming\NetBeans\8.2\config\Preferences\org\netbeans\modules\vagrant\general.properties_) and set
`vagrant.path=D:\\Vagrant\\bin\\vagrant.exe`
with double backslashes.
It works until next options edit.

**Comment by junichi11** [comment]
I cannot reproduce it in Windows 10.
Did you try to set `D:\Vagrant\bin\vagrant.exe` to the text field?

**Comment by voytass** [comment]
Hm, now it works. Maybe it was a Vagrant version issue? Now i have version 2.0.
Works "Search", "Browse" and manually set Vagrant script path. No more double backslashes required.
Thank you.
