### ISSUE TITLE
Configure Vagrant-Path relative to Project-Path

### ISSUE THREAD

**Issue by tkriener** [junichi11/netbeans-vagrant-plugin#50]
I would like to configure the path to the vagrantfile relatively to the project.
In our case that would be something like this in nb-configuration.xml of a maven-project 
`<org-netbeans-modules-vagrant.vagrant-path>../vagrant</org-netbeans-modules-vagrant.vagrant-path>`

An absolut Path won't make sense here, as this file is shared between all developers.

**Comment by junichi11** [comment]
Please give it a try: https://github.com/junichi11/netbeans-vagrant-plugin/releases/tag/v1.1.0 (1.1.0.1-dev)

**Comment by junichi11** [comment]
If you find a problem, please reopen this or create a new issue.
Thanks.

**Comment by tkriener** [comment]
It works, thanks for the quick response.
