### ISSUE TITLE
Cannot select a vagrantfile in Netbeans Vagrant Options 

### ISSUE THREAD

**Issue by fyodorovich** [junichi11/netbeans-vagrant-plugin#52]
I'm new to netbeans and trying to setup up the profile environment. I have a functional vagrant box which I run from terminal. When I am in Netbeans options -> Miscellaneous -> Vagrant -> General I cannot select the vagrantfile. Each time I browse to the location of the file and select it the response is "This is not a vagrant file". Of course it is a vagrant file.

I noticed on the netbeans forum that the vagrantfile must be named Vagrantfile or vagrantfile. In this case, the file name is Vagrantfile.

Netbeans 8.2, Vagrant plugin 1.1.0

**Comment by junichi11** [comment]
"Vagrant script" doesn't mean "vagrantfile". It means the Vagrant itself. Typically, vagrant or vagrant.exe.

**Comment by junichi11** [comment]
Also, see the README: https://github.com/junichi11/netbeans-vagrant-plugin/blob/master/README.md
