### ISSUE TITLE
Cannot select vagrant script on netbeans 12 LTS

### ISSUE THREAD

**Issue by sbamamoto** [junichi11/netbeans-vagrant-plugin#54]
Hi,
when trying to select Vagrantfile in the settings dialog I always get the message: No Vagrant script. 

Using netbeans 12.0 LTS & Vagrant 2.2.10

Ciao
   bama

**Comment by junichi11** [comment]
Did you set a Vagrant script path? see: https://github.com/junichi11/netbeans-vagrant-plugin#options
What does your vagrant script file name? Typically, it is `vagrant`, `vagrant.exe`, or `vagrant.sh`. Please set it.

**Comment by sbamamoto** [comment]
Ahh, OK Sorry, I thought I should set the Path to Vagrantfile itself. Now it works as expected thanks.

**Comment by junichi11** [comment]
No problem :)
